# App Engine configuration file for Next.js
# Alternative deployment option to Cloud Run

runtime: nodejs20

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  PORT: 8080

handlers:
  - url: /.*
    script: auto
    secure: always

