# Cloud Build configuration for automatic deployment from GitHub
# 
# Required substitution variables (set in trigger):
#   _SERVICE_NAME: Your Cloud Run service name (e.g., "Portfolio")
#   _IMAGE_NAME: Lowercase version for Docker image (e.g., "portfolio")
#   _REGION: GCP region (e.g., "us-central1")

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'my-portfolio'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
      - '.'
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  
  # Deploy to Cloud Run
  # Note: Cloud Run service names must be lowercase, so we use _IMAGE_NAME which should be lowercase
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_IMAGE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCS_BUCKET=rotating_image_collage_bucket,GCS_PREFIX=collage/'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
