# Cloud Build configuration for automatic deployment from GitHub
steps:
  # Convert service name to lowercase for Docker image (Docker requires lowercase)
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Convert _SERVICE_NAME to lowercase and save to file
        # Use _IMAGE_NAME if provided, otherwise convert _SERVICE_NAME
        if [ -n "$${_IMAGE_NAME:-}" ]; then
          IMG_NAME=$$(echo "$${_IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
        else
          IMG_NAME=$$(echo "$${_SERVICE_NAME}" | tr '[:upper:]' '[:lower:]')
        fi
        echo "$$IMG_NAME" > /workspace/image-name.txt
        echo "Using image name: $$IMG_NAME"
  
  # Build the Docker image (using lowercase image name)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMG_NAME=$$(cat /workspace/image-name.txt)
        docker build -t gcr.io/$$PROJECT_ID/$$IMG_NAME .
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMG_NAME=$$(cat /workspace/image-name.txt)
        docker push gcr.io/$$PROJECT_ID/$$IMG_NAME
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMG_NAME=$$(cat /workspace/image-name.txt)
        gcloud run deploy $${_SERVICE_NAME} \
          --image gcr.io/$$PROJECT_ID/$$IMG_NAME \
          --region $${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --port 3000 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10

# Store images in Container Registry
# Image name is determined dynamically in the build steps
# Using lowercase service name as fallback
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
